export default [
  {
    type: 'postgres',
    name: 'default',
    host: 'localhost',
    port: process.env.DB_PORT || 5432,
    username: process.env.DB_USER_NAME || 'postgres',
    synchronize: false,
    migrationsRun: true,
    logging: false,
    entities: ['src/entities/**/*.ts'],
    migrations: ['src/migrations/**/*.ts'],
    subscribers: ['src/subscribers/**/*.ts'],
    cli: {
      entitiesDir: 'src/entities',
      migrationsDir: 'src/migrations',
      subscribersDir: 'src/subscribers',
    },
  },
  {
    type: 'postgres',
    name: 'test',
    host: 'localhost',
    port: process.env.DB_PORT || 5432,
    username: process.env.DB_USER_NAME || 'postgres',
    synchronize: true,
    migrationsRun: false,
    logging: false,
    entities: ['src/entities/**/*.ts'],
    migrations: ['src/migrations/**/*.ts'],
    subscribers: ['src/subscribers/**/*.ts'],
    cli: {
      entitiesDir: 'src/entities',
      migrationsDir: 'src/migrations',
      subscribersDir: 'src/subscribers',
    },
  },
];
